# Generated by Django 4.0 on 2023-12-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='details',
            field=models.TextField(default=None),
        ),
    ]
